services:

  postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: url-redis
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      JWT_SECRET: my_super_secret_jwt_key_12345
    depends_on:
      - postgres

  url-service:
    build: ./url-service
    container_name: url-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: url_db
      JWT_SECRET: my_super_secret_jwt_key_12345
      REDIS_URL: redis://redis:6379 
    depends_on:
      - postgres
      - redis
