events {}

http {

    upstream auth_service {
        server auth-service:3001;
    }

    upstream url_service {
        server url-service:3002;
    }

    server {

        listen 80;

        location /api/auth/ {
            proxy_pass http://auth_service;
        }

        location /api/urls/ {
            proxy_pass http://url_service;
        }
    }
}
